/*CREATE TABLE Entreprise(
	ID_Entreprise INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1011) NOT NULL PRIMARY KEY
	-- start with (le nuéro a partir du quel on peut générer automatiquement)
	Raison_Sociale VARCHAR(40) NOT NULL,
	Adresse VARCHAR(60), 
	Ville VARCHAR(15), 
	Region VARCHAR(15), 
	Code_postal CHAR(10), 
	Pays VARCHAR(15), 
	Telephone VARCHAR(24) default NULL,
	Mail_Entreprise VARCHAR(40)
	
);

CREATE TABLE Contact (
	ID_Contact INT GENERATED BY DEFAULT AS IDENTITY  NOT NULL PRIMARY KEY,
	Nom VARCHAR(30) NOT NULL,
	Prenom VARCHAR(30) NOT NULL,
	Mail VARCHAR(40),
	Tel_portable VARCHAR(24),
	Tel_fixe VARCHAR(24),
	Fonction VARCHAR(40),
	Entreprise_contact INT NOT NULL,
	CONSTRAINT FK_Entreprise FOREIGN KEY (Entreprise) REFERENCES Entreprise(ID_Entreprise),
	
);

CREATE TABLE Etiquette (
	ID_Etiquette INT GENERATED BY DEFAULT AS IDENTITY (START WITH 13) NOT NULL PRIMARY KEY, 
	Intitule VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE Commentaire (
	ID_Commentaire INT GENERATED BY DEFAULT AS IDENTITY (START WITH 9) NOT NULL PRIMARY KEY, 
	Texte VARCHAR(255) DEFAULT NULL,
	Date_Commentaire default CURRENT_DATE NOT NULL,
	Auteur VARCHAR(30) DEFAULT ('Marion'),
);

CREATE TABLE EntrepriseEtiquette (
	Entreprise_etq  INT REFERENCES Entreprise (ID_Entreprise),
	Etiquette_entreprise INT REFERENCES Etiquette (ID_Etiquette)
);

CREATE TABLE ContactEtiquette (
	Conatact_etq  INT REFERENCES Contact (ID_Contact),
	Etiquette_contact INT REFERENCES Etiquette (ID_Etiquette)
);

CREATE TABLE EntrepriseCommentaire (
	Entreprise_com  INT REFERENCES Entreprise (ID_Entreprise),
	Commenataire_entreprise INT REFERENCES Commentaire (ID_Commentaire)
);

CREATE TABLE ContactCommentaire (
	Conatact_com  INT REFERENCES Contact (ID_Contact),
	Commentaire_contact INT REFERENCES Commentaire (ID_Commentaire)
);*/